### ISSUE TITLE
Unreliable pageview tracking

### ISSUE THREAD

**Issue by kylenathan** [pgrippi/ember-cli-google-analytics#4]
At the moment this plugin only explicitly tracks the initial pageview/transition event on app boot. It then relies on GA to try deduce later transitions automatically. From trying it out this seems to be very unreliable.

Solution is to manually track the transitions by adding an observer to your router. E.g:

    var Router = Ember.Router.extend({
        location: config.locationType,
        pageviewToGA: function() {
            return ga('send', 'pageview', {
                'page': this.get('url'),
                'title': this.get('url')
            }
        }.on('didTransition')
    });

But if you add this you end up with a duplicate initial pageview event (one send from html code injection from the addon, and one from the router transition).

**Comment by pgrippi** [comment]
That's a good point, I had assumed users of this addon added their own code to track page views (much like the snippet you have), but I missed the double page view issue.

I've merged your pull request and I've also added a mixin with your code above so that people can easily add tracking to route transitions. I added a small blurb to the [README](https://github.com/pgrippi/ember-cli-google-analytics#usage)

**Comment by pgrippi** [comment]
I've published [version 1.3.0](https://github.com/pgrippi/ember-cli-google-analytics/releases/tag/v1.3.0) here and on npm with these changes

**Comment by kylenathan** [comment]
Great stuff, thanks @pgrippi
